[project]
name = "evers.dev"
version = "0.1.0"
description = "My webpage"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "click<=8.2.1",
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.7.0",
]
